name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: act-windows-006

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Custom Node.js Setup Action
      uses: ./.github/actions/setup-node
      with:
         node-version: "18"
         install-command: "npm install"

   
