name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: act-windows-006

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # - name: Verify Action File Exists
    #   run: |
    #     if (Test-Path ".github/actions/setup-node/action.yml") {
    #         echo "✅ action.yml found"
    #       } else {
    #         echo "❌ action.yml NOT found"
    #         exit 1
    #       }
    #     shell: pws

    - name: Run Custom Node.js Setup Action
      if: success()
      uses: ./.github/actions/setup-node
      with:
         node-version: "18"
         install-command: "npm install"

   
